### ISSUE TITLE
Getting error opening this sample

### ISSUE THREAD

**Issue by NelzkieCoder** [googlesamples/android-NotificationChannels#17]
Process: com.example.android.notificationchannels, PID: 6386
                                                                                        java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/NotificationChannel;
                                                                                            at com.example.android.notificationchannels.NotificationHelper.<init>(NotificationHelper.java:45)
                                                                                            at com.example.android.notificationchannels.MainActivity.onCreate(MainActivity.java:61)
                                                                                            at android.app.Activity.performCreate(Activity.java:5990)
                                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.NotificationChannel" on path: DexPathList[[zip file "/data/app/com.example.android.notificationchannels-2/base.apk", zip file "/data/app/com.example.android.notificationchannels-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.android.notificationchannels-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.android.notificationchannels-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.android.notificationchannels-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.android.notificationchannels-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.android.notificationchannels-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.android.notificationchannels-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.android.notificationchannels-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.android.notificationchannels-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.android.notificationchannels-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.android.notificationchannels-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                            at com.example.android.notificationchannels.NotificationHelper.<init>(NotificationHelper.java:45) 
                                                                                            at com.example.android.notificationchannels.MainActivity.onCreate(MainActivity.java:61) 
                                                                                            at android.app.Activity.performCreate(Activity.java:5990) 
                                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278) 
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                            at android.os.Looper.loop(Looper.java:135) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                                            at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                                        	Suppressed: java.lang.ClassNotFoundException: android.app.NotificationChannel
                                                                                            at java.lang.Class.classForName(Native Method)
                                                                                            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                            		... 16 more
                                                                                         Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by aimanzakikagzi** [comment]
I am facing the same issue. Are there any solutions to this?

**Comment by GuillaumeBourge** [comment]
You are probably trying to deploy the sample on device <API26, there are no test/prevent on API version in the sample code. It will works only on 26+
@google-automerger you should inform people in the docs or add a test in the code

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
